[package]
name = "cairo_python_bindings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
compiler = { path = "../compiler" }
runner = { path = "../runner" }
sierra_to_casm = { path = "../sierra_to_casm" }

[lib]
name = "cairo_python_bindings"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.10.1"
features = ["extension-module"]