[package]
name = "cairo-lang-runner"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Basic cairo runner."

[dependencies]
anyhow.workspace = true
cairo-vm.workspace = true
clap.workspace = true
cairo-lang-compiler = { path = "../cairo-lang-compiler", version = "0.1.0" }
cairo-lang-casm = { path = "../cairo-lang-casm", version = "0.1.0" }
cairo-lang-diagnostics = { path = "../cairo-lang-diagnostics", version = "0.1.0" }
num-bigint.workspace = true
cairo-lang-sierra = { path = "../cairo-lang-sierra", version = "0.1.0" }
cairo-lang-sierra-ap-change = { path = "../cairo-lang-sierra-ap-change", version = "0.1.0" }
cairo-lang-sierra-gas = { path = "../cairo-lang-sierra-gas", version = "0.1.0" }
cairo-lang-sierra-generator = { path = "../cairo-lang-sierra-generator", version = "0.1.0" }
cairo-lang-sierra-to-casm = { path = "../cairo-lang-sierra-to-casm", version = "0.1.0" }
cairo-lang-utils = { path = "../cairo-lang-utils", version = "0.1.0" }
itertools.workspace = true
salsa.workspace = true
thiserror.workspace = true

[[bin]]
name = "cairo-run"
path = "src/cli.rs"
